backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "english_notes"
    label: "English Notes"
    folder: "src/content/english-notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Chapter", name: "chapter", widget: "number" }
      - { label: "Class", name: "classLevel", widget: "number" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }